### PR TITLE
Images

### PR DESCRIPTION
**Pull request by efl7a**
Added an images branch.  I have added images as buttons for the save/remove job buttons.  If you like that I was thinking of adding a Polaroid for the new resume (you know, take a pic of yourself).  I would also like to decrease the size of your main image, but that of course is your call.

### CODE REVIEW

**Comment by willywos** [comment]
Thanks for taking a look at these. I think it might be a good idea to update these to images. Here's what I was thinking about this. What if you shrink them down a little and just use the images without the text in them. This way they can be clickable and instead of buttons be more like hyperlinks. Maybe move them over to the right side? or underneath like it is now might also work.

image

This is a really rough mockup but let me know what you think. If you want to send a pic/mock of what you are thinking about that would work also if it's easier for you instead of doing all the work.

**Comment by efl7a** [comment]
@willywos - yes, after I submitted the PR, I started to worry about the responsiveness of those buttons on smaller screens. I was just trying to get a funkier font. Any chance you have access to a spray paint type font that you can embed into the page?  The only ones I found are free, but not when embedded.
I'll work toward the mockup and see what I can do.  
Just for my own knowledge, what did you use to make the mockup above?  I haven't done that before.

**Comment by efl7a** [comment]
@willywos - Look at these changes and see what you think.  They do look better.  
I still think a cool font would be nice.  Check these out.
https://www.fontsquirrel.com/fonts/code-pro
https://www.fontsquirrel.com/fonts/exo

OK, thanks for letting me work on your site.  I like the idea!

**Comment by willywos** [comment]
@efl7a Yeah I don't have access at the moment to other fonts. I know the one that's used in the header image was a 80's style font I got somewhere for free. I think it was called lazer. I wish I still had it haha. I like the Exo one, that looks kind of neat. We also have [https://fontawesome.com/v4.7.0/](font awesome icons) integrated into the project if those are helpful at all?

As far as the mockup goes, I use a app called. [https://www.sketchapp.com/](Sketch). They have a free trial and it's much easier to learn than like photoshop or affinity.

**Comment by efl7a** [comment]
@willywos This may be too much, but I like the uniformity.  I don't like that in smaller font the Lazer 84 is a bit harder to read.

**Comment by willywos** [comment]
@efl7a Hey that's kind of neat. I like the font on the buttons. What if you change the letter spacing in the css for the buttons to like 2px? That might help make it easier to read with that font. 

I was thinking about the images and they might be a little hard to understand, like I could see someone asking why a gameboy is there haha. What do you think? 

Looking good though 👍

**Comment by efl7a** [comment]
@willywos - I agree with you.  I started out with the eighties graphics, but I like the common font and background better.  I don't think you need both.  I will take out the graphics (but leave them in the assets just in case someone else can use them for a cool effect) and try to make the font more readable.

**Comment by efl7a** [comment]
@willywos - That is about as much as I can do.  It has been a learning experience.

**Comment by willywos** [comment]
@efl7a haha no worries. Thank you so much for your hard work! You rock! I’ll update it tonight and have a happy hacktoberfest!

**Pull request merged**
